### ISSUE TITLE
Port to CircleCI 2.0

### ISSUE THREAD

**Issue by Lestropie** [BIDS-Apps/example#26]
Any BIDS Apps that were initially built using this example as a template will no longer pass Continuous Integration testing:

https://circleci.com/sunset1-0/

It would likely be useful for existing and future BIDS App developers if this baseline example repo were updated from CircleCI 1.0 to 2.0, and the requisite changes encapsulated within the corresponding PR.

**Comment by chrisgorgo** [comment]
Thanks!

**Comment by ntraut** [comment]
@chrisgorgo I think you have to reactivate something in CircleCI because it still says that the project is not configured for CircleCI 2.0.

**Comment by sappelhoff** [comment]
I just reactivated it, it should be building now. I just closed and re-opened #23 to check.

However, there has been an error in the build: https://app.circleci.com/pipelines/github/BIDS-Apps/example/1/workflows/49fac588-9f30-420f-b4c0-678a80f71ad8/jobs/121/steps

cc @ntraut

**Comment by ntraut** [comment]
Hi, I think you have to set the following environment variables in your project settings in CircleCi:

`DOCKER_EMAIL`, `DOCKER_PASS` and `DOCKER_USER`

**Comment by sappelhoff** [comment]
They seem to be set: 

![image](https://user-images.githubusercontent.com/9084751/81941918-be47e700-95f9-11ea-958c-66336d44346f.png)

If they weren't, then projects like [BIDS/Apps/SPM](https://github.com/BIDS-Apps/SPM/blob/master/.circleci/config.yml) wouldn't work. Must be a different issue.

**Comment by ntraut** [comment]
For me it's set up only for the example repository, I don't know if there is a way to do it for the whole organization.

![circleci](https://user-images.githubusercontent.com/22977927/82037722-d58edf00-96a2-11ea-8830-f6f7cd8c9be8.PNG)

https://app.circleci.com/pipelines/github/ntraut/example/26/workflows/2a9b7737-8441-43f5-8ab0-ecb9efe0a4f9/jobs/37/steps
