### ISSUE TITLE
Look at creating a releasable package

### ISSUE THREAD

**Issue by berleant** [BIDS-Apps/example#7]
to encapsulate shared code that all compliant bids apps will have

**Comment by dPys** [comment]
That will be our next project for Neurohackweek 2017 in Seattle. Lots of kinks to work out first, so feel free to contribute any Pull Requests :-) We are especially hoping to see some really excellent statistical contributions for lines 571-652...

**Comment by chrisgorgo** [comment]
lines 571-652? I'm a bit lost. Is the project you mentioned aimed at turning PyNets into a BIDS App?

**Comment by Remi-Gau** [comment]
closing for now: reopen if still relevant
